services:
  mongo:
    image: mongo:7
    container_name: expense-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: expense-mailpait
    restart: unless-stopped
    ports:
    - "8025:8025"
    - "1025:1025"

  backend:
    build: ./backend
    container_name: expense-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      mailpit:
        condition: service_started
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/expense_manager
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - MAIL_FROM=norpely@supherman.com 
    volumes:
      - uploads-data:/app/uploads

  frontend:
    build: ./frontend
    container_name: expense-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo-data:
  uploads-data: